service: iaq-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
  httpApi:
    payload: "2.0"
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:ap-southeast-2:573131509880:table/IAQData
  
functions:
  app:
    handler: index.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-offline

package:
  exclude:
    - .gitignore
    - .git/**
